/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.testunited.examples.learnright.course.test.api;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.TestInstance.Lifecycle;

@TestInstance(Lifecycle.PER_CLASS)
public class POST_Test extends CourseApiTestBase{
	
	private final String courseGood = 
			"{\n" + 
			"	\"id\":1, \n" + 
			"	\"bookTitleId\": 1, \n" + 
			"	\"name\":\"Sams Teach Yourself Java in 21 Days - June 2019 Intake\", \n" + 
			"	\"startDate\": \"2019-06-01\", \n" + 
			"	\"endDate\":\"2019-06-21\"\n" + 
			"}";

	private final String courseBad = 			
			"{\n" + 
			"	\"id\":1, \n" + 
			"	\"bookTitleId\": 1, \n" + 
			"	\"name\":\"Sams Teach Yourself Java in 21 Days - June 2019 Intake\", \n" + 
			"	\"startDate\": \"2019-06-01\", \n" + 
			"	\"endDate\":\"2019-06-21\"\n" + 
			"}";

	@BeforeEach
	@Override
	public void setup() {
		super.setup();
	}

	@Test()
	public void success_statuscode() {

		RequestSpecification request = RestAssured.given();

// Add a header stating the Request body is a JSON
		request.header("Content-Type", "application/json");

// Add the Json to the body of the request
		request.body(courseGood);

// Post the request and check the response
		request.post("/").then().assertThat().statusCode(201);
	}
}
